### ISSUE TITLE
star-star binaries created by triple-star interactions

### ISSUE THREAD

**Issue by Steve-Hawk** [Kkritos/Rapster#1]
the variable `aStarStar_min` seems not to have been defined here, so the condition of the `if` will not be satisfied all the time.
https://github.com/Kkritos/Rapster/blob/6b85409ae022639d0556f9db9997a23d55daa0d6/rapster.py#L868-L889

**Comment by Kkritos** [comment]
The variable `aStarStar_min` is substituted by `aBin_min`.
