### ISSUE TITLE
t_form of BBHs from ZLK merger (when triple systems exist) is always zero

### ISSUE THREAD

**Issue by Steve-Hawk** [Kkritos/Rapster#2]
https://github.com/Kkritos/Rapster/blob/f21140d83333426959148a87318366681f946f5d/rapster.py#L2300

the update of running iteration index needs to be moved after 

https://github.com/Kkritos/Rapster/blob/f21140d83333426959148a87318366681f946f5d/rapster.py#L2319-L2322

when use `triples[i][15]`

**Comment by Kkritos** [comment]
Indeed, I have now moved ``i=i-1`` after storing data in the list.
