### ISSUE TITLE
sample size (size=2) sometimes is larger than the size of mBH

### ISSUE THREAD

**Issue by Steve-Hawk** [Kkritos/Rapster#3]
when entering `if k3bBH > 0:`, `N_BH_sin` has not been well updated by a potential `N_BH_sin = mBH.size` before the `if` condition. 
https://github.com/Kkritos/Rapster/blob/f21140d83333426959148a87318366681f946f5d/rapster.py#L1095
will report an error when `mBH` is smaller than 2, which usually happens at the end of a simulation.

**Comment by Kkritos** [comment]
Now, ``N_BH_sin=mBH.size`` is added before the redefinition of ``k3bBH`` and ``kPair``, as the number of single BHs may vary within the current step.
